name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting:
    name: Check Formatting using Black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Formatting checkers
      run: |
        python -m pip install --upgrade pip
        pip install black==19.10b0
    - name: Check Formatting using Black
      run: |
        black --check .

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./tools/setup_xvfb.sh
      name: 'Setup xvfb'   
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install --upgrade "pytest<5.4" pytest-sugar pytest-cov pytest-mock pytest-timeout
    - name: Install bfieldtools
      run: python setup.py install
    - name: Run Pytest with xvfb
      run: |
        pytest --cov=bfieldtools ./tests
        # Push coverage to codecov.io
        bash <(curl -s https://codecov.io/bash)
